module.exports = {
  MAX_FAVORITES: 5,
  MAX_ACTIVITIES: 50,
  MAX_COLLECTIONS: 20,
  MAX_COLLECTION_ANIME: 100,
  MAX_BIO_LENGTH: 500,
  MAX_COLLECTION_NAME_LENGTH: 50,
  MAX_COLLECTION_DESC_LENGTH: 200,
  MAX_REVIEW_LENGTH: 5000,
  MAX_TIERLIST_DESC_LENGTH: 500,
  DEFAULT_PAGINATION_LIMIT: 50,
  MAX_PAGINATION_LIMIT: 100,
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX: 100,
  SYNC_BATCH_DELAY_MS: 400,
  SYNC_RETRY_DELAY_MS: 1000,
  SYNC_RATE_LIMIT_WAIT_MS: 1500,
  SYNC_RATE_LIMIT_MAX_WAIT_MS: 5000,
  DEFAULT_RETRIES: 1,
  TOKEN_EXPIRY_BUFFER_MS: 60 * 1000,
  EMAIL_VERIFICATION_EXPIRY_HOURS: 24,
  PASSWORD_RESET_EXPIRY_HOURS: 1,
  DAILY_BONUS_XP: 10,
  STREAK_BONUS_XP: 5,
  MAX_DAILY_BONUS_STREAK: 7,
  FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:3000',
  BACKEND_URL: process.env.BACKEND_URL || 'http://localhost:5000',
  CLIENT_URL: process.env.CLIENT_URL || process.env.FRONTEND_URL || 'http://localhost:3000',
  GRAPHQL_TIMEOUT_MS: 6000,
  MAL_LIST_LIMIT: 500,
  ANILIST_PER_PAGE: 50,
  TOKEN_EXPIRY_BUFFER_SECONDS: 3600,
  CACHE_TTL_MS: 5 * 60 * 1000,
  CACHE_MAX_ENTRIES: 50,
  SYNOPSIS_MAX_LENGTH: 500,
  SYNOPSIS_SHORT_LENGTH: 250,
  MAX_PAGE_NUMBER: 5000,
};

module.exports.NOTIFICATION_SETTINGS = {
  EMAIL_NOTIFS: { key: 'emailNotifs', default: true },
  NEW_EPISODES: { key: 'newEpisodes', default: true },
  COMMUNITY_ACTIVITY: { key: 'communityActivity', default: false },
  FRIENDS_ACTIVITY: { key: 'friendsActivity', default: false },
  SYSTEM_UPDATES: { key: 'systemUpdates', default: true },
  WEEKLY_RECS: { key: 'weeklyRecs', default: true },
  PUSH_NOTIFS: { key: 'pushNotifs', default: true },
  NEWS_NOTIFICATIONS: { key: 'newsNotifications', default: true },
  NEW_EPISODE_ALERTS: { key: 'newEpisodeAlerts', default: true },
  COMMENT_REPLIES: { key: 'commentReplies', default: true },
  FRIEND_REQUESTS: { key: 'friendRequests', default: true },
  ANIME_RECS: { key: 'animeRecs', default: false },
  NEW_FEATURES: { key: 'newFeatures', default: false },
};

module.exports.NOTIFICATION_SETTINGS_KEYS = Object.values(module.exports.NOTIFICATION_SETTINGS).map(s => s.key);
module.exports.NOTIFICATION_DEFAULTS = Object.fromEntries(
  Object.values(module.exports.NOTIFICATION_SETTINGS).map(s => [s.key, s.default])
);