name = "anime-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
ALLOWED_DOMAINS = "reanime.to,flixcloud.cc,animeslayer.to,kuudere.to"
WORKER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
WORKER_REFERER = "https://www.google.com/"
